--liquibase formatted sql
--changeset dmitry_petrov:000_1_schema

CREATE TABLE IF NOT EXISTS public.role
(
    id         bigint                      NOT NULL GENERATED BY DEFAULT AS IDENTITY
        ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    title      character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT role_pk PRIMARY KEY (id),
    CONSTRAINT role_title_uq UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS public."app-user"
(
    id         bigint                                              NOT NULL GENERATED BY DEFAULT AS IDENTITY
        ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp without time zone                         NOT NULL DEFAULT now(),
    updated_at timestamp without time zone                         NOT NULL DEFAULT now(),
    username   character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password   character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role_id    bigint                                              NOT NULL,
    CONSTRAINT "app-user_pk" PRIMARY KEY (id),
    CONSTRAINT "app-user_username_uq" UNIQUE (username),
    CONSTRAINT "role_app-user_fk" FOREIGN KEY (role_id)
        REFERENCES public.role (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.tag
(
    id         bigint                                              NOT NULL GENERATED BY DEFAULT AS IDENTITY
        ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp without time zone                         NOT NULL DEFAULT now(),
    updated_at timestamp without time zone                         NOT NULL DEFAULT now(),
    tag        character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tag_pk PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS public."tag-collection"
(
    id         bigint                      NOT NULL GENERATED BY DEFAULT AS IDENTITY
        ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT "tag-collection_pk" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."tag-collection_tag"
(
    id                  bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY
        ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    tag_id              bigint NOT NULL,
    "tag-collection_id" bigint NOT NULL,
    CONSTRAINT "tag-collection_tag_pk" PRIMARY KEY (id),
    CONSTRAINT "tag-collection_tag_fk" FOREIGN KEY ("tag-collection_id")
        REFERENCES public."tag-collection" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION,
    CONSTRAINT "tag_tag-collection_fk" FOREIGN KEY (tag_id)
        REFERENCES public.tag (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.course
(
    id                  bigint                                              NOT NULL GENERATED BY DEFAULT AS IDENTITY
        ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at          timestamp without time zone                         NOT NULL DEFAULT now(),
    updated_at          timestamp without time zone                         NOT NULL DEFAULT now(),
    title               character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description         character varying(1000) COLLATE pg_catalog."default",
    "app-user_id"       bigint                                              NOT NULL,
    "tag-collection_id" bigint,
    "position"          integer                                                      DEFAULT 100,
    CONSTRAINT course_pk PRIMARY KEY (id),
    CONSTRAINT "app-user_course_fk" FOREIGN KEY ("app-user_id")
        REFERENCES public."app-user" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION,
    CONSTRAINT "course_tag-collection_fk" FOREIGN KEY ("tag-collection_id")
        REFERENCES public."tag-collection" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public."course-step"
(
    id         bigint                      NOT NULL GENERATED BY DEFAULT AS IDENTITY
        ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    date       date                        NOT NULL,
    assessment integer                     NOT NULL,
    course_id  bigint                      NOT NULL,
    CONSTRAINT day_pk PRIMARY KEY (id),
    CONSTRAINT day_course_id_date_uq UNIQUE (course_id, date),
    CONSTRAINT course_day_fk FOREIGN KEY (course_id)
        REFERENCES public.course (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION
)