--liquibase formatted sql
--changeset dmitry_petrov:001

CREATE TABLE IF NOT EXISTS public.task
(
    id                  bigint                                              NOT NULL GENERATED BY DEFAULT AS IDENTITY
        ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at          timestamp without time zone                         NOT NULL DEFAULT now(),
    updated_at          timestamp without time zone                         NOT NULL DEFAULT now(),
    title               character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description         character varying(10000) COLLATE pg_catalog."default",
    "position"          integer                                                      DEFAULT 100,
    "priority"          integer                                                      DEFAULT 100,
    "done"              bool                                                         DEFAULT false,
    "finished_at"       timestamp without time zone,
    "app-user_id"       bigint                                              NOT NULL,
    "parent_id"         bigint,
    "tag-collection_id" bigint,

    CONSTRAINT task_pk PRIMARY KEY (id),
    CONSTRAINT "app-user_course_fk" FOREIGN KEY ("app-user_id")
        REFERENCES public."app-user" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION,
    CONSTRAINT "task_task_fk" FOREIGN KEY ("parent_id")
        REFERENCES public."task" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT "task_tag-collection_fk" FOREIGN KEY ("tag-collection_id")
        REFERENCES public."tag-collection" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION
);
