--liquibase formatted sql
--changeset dmitry_petrov:003

CREATE TABLE IF NOT EXISTS public."day-description"
(
    id                  bigint                                              NOT NULL GENERATED BY DEFAULT AS IDENTITY
        ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at          timestamp without time zone                         NOT NULL DEFAULT now(),
    updated_at          timestamp without time zone                         NOT NULL DEFAULT now(),
    date                date                                                NOT NULL,
    description         character varying(2000) COLLATE pg_catalog."default",
    "app-user_id"       bigint                                              NOT NULL,
    "tag-collection_id" bigint,

    CONSTRAINT "day-description_pk" PRIMARY KEY (id),
    CONSTRAINT "app-user_day-description_fk" FOREIGN KEY ("app-user_id")
        REFERENCES public."app-user" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION,
    CONSTRAINT "day-description_tag-collection_fk" FOREIGN KEY ("tag-collection_id")
        REFERENCES public."tag-collection" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION
);
